// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConversationKind = "private";

export type ConversationParticipantKind = "member" | "contact";

export type ConversationProfile = { conversationId: string, workspaceId: string, kind: ConversationKind, title: string, participantKind: ConversationParticipantKind, participantId: string, createdAtMs: number, updatedAtMs: number, lastActivityAtMs: number, };

export type StartPrivateConversationRequest = { workspaceId: string, participantKind: ConversationParticipantKind, participantId: string, };

export type StartPrivateConversationResult = { conversation: ConversationProfile, created: boolean, };
