// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConversationKind = "channel" | "group" | "private";

export type ConversationMemberSummary = { memberId: string, displayName: string, instanceLabel: string, };

export type ConversationParticipantKind = "member" | "contact";

export type ConversationProfile = { conversationId: string, workspaceId: string, kind: ConversationKind, title: string, isDefault: boolean, isPinned: boolean, unreadCount: number, lastMessagePreview: string | null, participantKind: ConversationParticipantKind | null, participantId: string | null, members: Array<ConversationMemberSummary>, createdAtMs: number, updatedAtMs: number, lastActivityAtMs: number, };

export type CreateGroupConversationRequest = { workspaceId: string, title: string, memberIds: Array<string>, };

export type CreateGroupConversationResult = { conversation: ConversationProfile, conversations: Array<ConversationProfile>, };

export type ListConversationsRequest = { workspaceId: string, };

export type ListConversationsResult = { conversations: Array<ConversationProfile>, };

export type StartPrivateConversationRequest = { workspaceId: string, participantKind: ConversationParticipantKind, participantId: string, };

export type StartPrivateConversationResult = { conversation: ConversationProfile, created: boolean, };

export type UpdateGroupConversationMembersRequest = { workspaceId: string, conversationId: string, memberIds: Array<string>, };

export type UpdateGroupConversationMembersResult = { conversation: ConversationProfile, conversations: Array<ConversationProfile>, };
