// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { code: string, message: string, severity: AppErrorSeverity, recoverable: boolean, userAction: string | null, details: string | null, correlationId: string | null, };

export type AppErrorSeverity = "info" | "warning" | "error";
