// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberProfile } from "./member";

export type ContactInviteSource = "adminContactInvite";

export type ContactKind = "contact" | "administrator";

export type ContactProfile = { contactId: string, displayName: string, contactKind: ContactKind, inviteSource: ContactInviteSource, notes: string | null, sourceLabel: string | null, createdAtMs: number, updatedAtMs: number, };

export type CreateContactRequest = { displayName: string, contactKind: ContactKind, notes: string | null, sourceLabel: string | null, workspaceId: string | null, };

export type CreateContactResult = { contact: ContactProfile, contacts: Array<ContactProfile>, adminMember: MemberProfile | null, };

export type DeleteContactRequest = { contactId: string, };

export type DeleteContactResult = { deletedContactId: string, contacts: Array<ContactProfile>, };

export type ListContactsRequest = Record<symbol, never>;

export type ListContactsResult = { contacts: Array<ContactProfile>, };

export type UpdateContactRequest = { contactId: string, displayName: string, contactKind: ContactKind, notes: string | null, sourceLabel: string | null, };

export type UpdateContactResult = { contact: ContactProfile, contacts: Array<ContactProfile>, };
