// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataIntegrityCheckResult = { checkId: string, category: StorageCategory, status: DataIntegrityStatus, severity: DataIntegritySeverity, message: string, affectedPaths: Array<string>, userAction: string | null, details: string | null, };

export type DataIntegrityReport = { schemaVersion: number, reportId: string, generatedAtMs: number, manifest: Array<StorageManifestEntry>, checks: Array<DataIntegrityCheckResult>, totalChecks: number, passedChecks: number, failedChecks: number, skippedChecks: number, hasFailures: boolean, batched: boolean, };

export type DataIntegritySeverity = "info" | "warning" | "error";

export type DataIntegrityStatus = "passed" | "failed" | "skipped";

export type DataIntegrityValidateRequest = { workspaceRoot: string | null, };

export type DataIntegrityValidateResult = { report: DataIntegrityReport, };

export type StorageCategory = "storageManifest" | "workspaceMetadata" | "workspaceRegistry" | "workspaceFallbacks" | "memberProfiles" | "contactProfiles" | "conversationRecords" | "conversationMembers" | "messageRecords" | "conversationReadPositions" | "privateConversations";

export type StorageFormat = "json" | "sqlite";

export type StorageManifestEntry = { id: string, owner: StorageOwner, category: StorageCategory, description: string, pathPolicy: StoragePathPolicy, relativePath: string | null, fileName: string | null, format: StorageFormat, schemaVersion: number, readers: Array<string>, writers: Array<string>, privacyClass: StoragePrivacyClass, fixtureRequired: boolean, validationCheckId: string, notes: string, };

export type StorageOwner = "workspace" | "member" | "contact" | "chat";

export type StoragePathPolicy = "workspaceLocalRelative" | "appDataFile" | "appDataWorkspaceFile";

export type StoragePrivacyClass = "localPath" | "appState" | "workspaceData";
