// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationNavigationAction = { schemaVersion: number, kind: NotificationNavigationKind, workspaceId: string | null, conversationId: string | null, memberId: string | null, updatedAtMs: number, sourceWindowLabel: string | null, };

export type NotificationNavigationKind = "allUnread" | "conversation" | "memberTerminal";

export type NotificationNavigationPendingRequest = Record<symbol, never>;

export type NotificationNavigationPendingResult = { action: NotificationNavigationAction | null, };

export type NotificationNavigationRequest = { kind: NotificationNavigationKind, workspaceId: string | null, conversationId: string | null, memberId: string | null, sourceWindowLabel: string | null, };

export type NotificationNavigationResult = { action: NotificationNavigationAction, };

export type NotificationTrayState = { unreadCount: number, badgeLabel: string | null, hasUnread: boolean, };

export type NotificationUnreadConversation = { conversationId: string, title: string, unreadCount: number, lastMessagePreview: string | null, terminalMemberId: string | null, updatedAtMs: number, };

export type NotificationUnreadSummary = { schemaVersion: number, workspaceId: string | null, workspaceName: string | null, totalUnreadCount: number, conversations: Array<NotificationUnreadConversation>, tray: NotificationTrayState, updatedAtMs: number, sourceWindowLabel: string | null, };

export type NotificationUnreadSummaryRequest = Record<symbol, never>;

export type NotificationUnreadSummaryResult = { summary: NotificationUnreadSummary, };

export type NotificationUnreadUpdateRequest = { workspaceId: string | null, workspaceName: string | null, conversations: Array<NotificationUnreadConversation>, sourceWindowLabel: string | null, };

export type NotificationUnreadUpdateResult = { summary: NotificationUnreadSummary, };
