// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLanguage, AppTheme } from "./workspace";

export type AppPreferencesSettingsSnapshot = { schemaVersion: number, theme: AppTheme, language: AppLanguage, createdAtMs: number, updatedAtMs: number, };

export type DeleteUploadedProfileAvatarRequest = Record<symbol, never>;

export type DeleteUploadedProfileAvatarResult = { profile: ProfileSettingsSnapshot, };

export type GetProfileSettingsRequest = Record<symbol, never>;

export type GetProfileSettingsResult = { profile: ProfileSettingsSnapshot, };

export type ProfileAvatarKind = "placeholder" | "preset" | "uploaded";

export type ProfileAvatarSnapshot = { kind: ProfileAvatarKind, presetId: string | null, uploadId: string | null, sourceFileName: string | null, contentType: string | null, sizeBytes: number | null, libraryRelativePath: string | null, previewDataUrl?: string, updatedAtMs: number, };

export type ProfileSettingsSnapshot = { schemaVersion: number, displayName: string, timezone: string, status: ProfileStatus, statusMessage: string | null, avatar: ProfileAvatarSnapshot | null, createdAtMs: number, updatedAtMs: number, };

export type ProfileStatus = "online" | "offline" | "working" | "doNotDisturb";

export type ResetProfileAvatarRequest = Record<symbol, never>;

export type ResetProfileAvatarResult = { profile: ProfileSettingsSnapshot, };

export type SelectProfileAvatarPresetRequest = { presetId: string, };

export type SelectProfileAvatarPresetResult = { profile: ProfileSettingsSnapshot, };

export type UpdateProfileSettingsRequest = { displayName: string | null, timezone: string | null, status: string | null, statusMessage: string | null, };

export type UpdateProfileSettingsResult = { profile: ProfileSettingsSnapshot, };

export type UploadProfileAvatarRequest = { sourcePath: string, };

export type UploadProfileAvatarResult = { profile: ProfileSettingsSnapshot, };
