// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegisteredWindow } from "./workspace";

export type TerminalAttachRequest = { terminalSessionId: string | null, };

export type TerminalAttachResult = { session: TerminalSessionProfile, };

export type TerminalCloseRequest = { terminalSessionId: string, };

export type TerminalCloseResult = { session: TerminalSessionProfile, };

export type TerminalEnvironmentKind = "shell" | "builtInAiCli" | "customCli";

export type TerminalEnvironmentProfile = { schemaVersion: number, environmentId: string, label: string, kind: TerminalEnvironmentKind, source: TerminalEnvironmentSource, command: string, resolvedPath: string | null, memberId: string | null, status: TerminalEnvironmentStatus, message: string, userAction: string, details: string | null, };

export type TerminalEnvironmentSource = "system" | "memberRuntime";

export type TerminalEnvironmentStatus = "available" | "missing" | "invalid";

export type TerminalEnvironmentsListRequest = Record<symbol, never>;

export type TerminalEnvironmentsListResult = { environments: Array<TerminalEnvironmentProfile>, };

export type TerminalInputRequest = { terminalSessionId: string, input: string, };

export type TerminalInputResult = { session: TerminalSessionProfile, };

export type TerminalOpenRequest = { memberId: string | null, attachCurrent: boolean, };

export type TerminalOpenResult = { window: RegisteredWindow, windowOpened: boolean, session: TerminalSessionProfile, sessionCreated: boolean, };

export type TerminalOutputEventPayload = { schemaVersion: number, terminalSessionId: string, workspaceId: string, memberId: string | null, seq: number, chunk: string, kind: TerminalStreamKind, emittedAtMs: number, };

export type TerminalResizeRequest = { terminalSessionId: string, cols: number, rows: number, };

export type TerminalResizeResult = { session: TerminalSessionProfile, };

export type TerminalSessionExitReason = { code: string, message: string, occurredAtMs: number, };

export type TerminalSessionProfile = { schemaVersion: number, terminalSessionId: string, workspaceId: string, memberId: string | null, title: string, status: TerminalSessionStatus, cols: number, rows: number, snapshot: TerminalSessionSnapshot, exitReason: TerminalSessionExitReason | null, createdAtMs: number, updatedAtMs: number, };

export type TerminalSessionSnapshot = { lastSeq: number, text: string, truncated: boolean, updatedAtMs: number | null, };

export type TerminalSessionStatus = "starting" | "running" | "exited";

export type TerminalStatusEventPayload = { schemaVersion: number, terminalSessionId: string, workspaceId: string, memberId: string | null, title: string, status: TerminalSessionStatus, cols: number, rows: number, snapshot: TerminalSessionSnapshot, exitReason: TerminalSessionExitReason | null, emittedAtMs: number, };

export type TerminalStreamKind = "stdout" | "stderr" | "system";

export type TerminalTabCloseRequest = { tabId: string, };

export type TerminalTabCloseResult = { tab: TerminalTabProfile, session: TerminalSessionProfile, tabs: Array<TerminalTabProfile>, };

export type TerminalTabCreateRequest = { memberId: string | null, label: string | null, };

export type TerminalTabCreateResult = { tab: TerminalTabProfile, session: TerminalSessionProfile, tabs: Array<TerminalTabProfile>, };

export type TerminalTabProfile = { schemaVersion: number, tabId: string, workspaceId: string, terminalSessionId: string, memberId: string | null, label: string, shell: string, status: TerminalTabStatus, isPinned: boolean, sortIndex: number, createdAtMs: number, updatedAtMs: number, closedAtMs: number | null, };

export type TerminalTabRestoreRequest = { tabId: string, };

export type TerminalTabRestoreResult = { tab: TerminalTabProfile, session: TerminalSessionProfile, tabs: Array<TerminalTabProfile>, };

export type TerminalTabStatus = "open" | "closed";

export type TerminalTabUpdateRequest = { tabId: string, label: string | null, isPinned: boolean | null, sortIndex: number | null, };

export type TerminalTabUpdateResult = { tab: TerminalTabProfile, tabs: Array<TerminalTabProfile>, };

export type TerminalTabsListRequest = Record<symbol, never>;

export type TerminalTabsListResult = { tabs: Array<TerminalTabProfile>, activeTabId: string | null, };
