// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegisteredWindow } from "./workspace";

export type TerminalAttachRequest = { terminalSessionId: string | null, };

export type TerminalAttachResult = { session: TerminalSessionProfile, };

export type TerminalCloseRequest = { terminalSessionId: string, };

export type TerminalCloseResult = { session: TerminalSessionProfile, };

export type TerminalInputRequest = { terminalSessionId: string, input: string, };

export type TerminalInputResult = { session: TerminalSessionProfile, };

export type TerminalOpenRequest = { memberId: string | null, attachCurrent: boolean, };

export type TerminalOpenResult = { window: RegisteredWindow, windowOpened: boolean, session: TerminalSessionProfile, sessionCreated: boolean, };

export type TerminalOutputEventPayload = { schemaVersion: number, terminalSessionId: string, workspaceId: string, memberId: string | null, seq: number, chunk: string, kind: TerminalStreamKind, emittedAtMs: number, };

export type TerminalResizeRequest = { terminalSessionId: string, cols: number, rows: number, };

export type TerminalResizeResult = { session: TerminalSessionProfile, };

export type TerminalSessionProfile = { schemaVersion: number, terminalSessionId: string, workspaceId: string, memberId: string | null, title: string, status: TerminalSessionStatus, cols: number, rows: number, createdAtMs: number, updatedAtMs: number, };

export type TerminalSessionStatus = "starting" | "running" | "exited";

export type TerminalStatusEventPayload = { schemaVersion: number, terminalSessionId: string, workspaceId: string, memberId: string | null, title: string, status: TerminalSessionStatus, cols: number, rows: number, emittedAtMs: number, };

export type TerminalStreamKind = "stdout" | "stderr" | "system";
