// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppLanguage = "zh-CN" | "en-US";

export type AppPreferencesSnapshot = { theme: AppTheme, language: AppLanguage, };

export type AppTheme = "system" | "light" | "dark";

export type OpenWindowModeRequest = { mode: WindowMode, };

export type OpenWindowModeResult = { window: RegisteredWindow, opened: boolean, };

export type OpenWorkspaceInFileManagerRequest = { path: string, };

export type OpenWorkspaceInFileManagerResult = { path: string, opened: boolean, };

export type OpenWorkspaceRequest = { path: string, conflictResolution: WorkspaceConflictResolution | null, };

export type OpenWorkspaceResult = { status: WorkspaceOpenStatus, workspace: OpenedWorkspace | null, conflict: WorkspaceRegistryConflict | null, };

export type OpenedWorkspace = { rootPath: string, metadata: WorkspaceMetadata, created: boolean, accessMode: WorkspaceAccessMode, fallbackState: WorkspaceFallbackState | null, registryEntry: WorkspaceRegistryEntry, registryAction: WorkspaceRegistryAction, };

export type RecentWorkspaceEntry = { projectId: string, path: string, name: string, firstOpenedAtMs: number, lastOpenedAtMs: number, };

export type RegisterWindowRequest = { label: string, mode: WindowMode, };

export type RegisteredWindow = { label: string, mode: WindowMode, };

export type UpdateAppPreferencesRequest = { theme: AppTheme | null, language: AppLanguage | null, sourceWindowLabel: string | null, };

export type WindowContextSnapshot = { schemaVersion: number, currentWindow: RegisteredWindow, activeWorkspace: OpenedWorkspace | null, preferences: AppPreferencesSnapshot, updatedAtMs: number, sourceWindowLabel: string | null, };

export type WindowMode = "main" | "workspaceSelection" | "terminal" | "notificationPreview";

export type WorkspaceAccessMode = "readWrite" | "readOnly";

export type WorkspaceConflictResolution = "move" | "copy";

export type WorkspaceFallbackState = { reason: string, fallbackPath: string, limitedActions: Array<string>, userAction: string, };

export type WorkspaceMetadata = { schemaVersion: number, projectId: string, name: string, createdAtMs: number, updatedAtMs: number, };

export type WorkspaceOpenStatus = "opened" | "conflict" | "focusedExisting";

export type WorkspaceRegistryAction = "created" | "registered" | "reopened" | "moved" | "copied";

export type WorkspaceRegistryConflict = { projectId: string, name: string, existingPath: string, selectedPath: string, };

export type WorkspaceRegistryEntry = { projectId: string, path: string, name: string, firstOpenedAtMs: number, lastOpenedAtMs: number, };

export type WorkspaceSelectionStatus = { windowMode: WindowMode, canOpenWorkspace: boolean, recentWorkspaceCount: number, };
