pub mod app;
pub mod contracts;
pub mod domain;
pub mod gateway;
pub mod infrastructure;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(
            tauri_plugin_opener::Builder::new()
                .open_js_links_on_click(false)
                .build(),
        )
        .manage(app::workspace::WorkspaceRuntimeState::default())
        .manage(app::window_context::WindowContextRuntimeState::default())
        .manage(app::terminal::TerminalRuntimeState::default())
        .manage(app::notification::NotificationRuntimeState::default())
        .setup(|app| {
            app::notification::setup_native_tray(app)?;
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            gateway::workspace_commands::workspace_selection_status,
            gateway::workspace_commands::workspace_recent_list,
            gateway::workspace_commands::workspace_open,
            gateway::workspace_commands::workspace_open_in_file_manager,
            gateway::workspace_commands::window_context_get,
            gateway::workspace_commands::window_context_register,
            gateway::workspace_commands::app_preferences_update,
            gateway::workspace_commands::window_open_mode,
            gateway::data_integrity_commands::data_integrity_validate,
            gateway::diagnostics_commands::diagnostics_run_start,
            gateway::diagnostics_commands::diagnostics_run_complete,
            gateway::diagnostics_commands::diagnostics_event_record,
            gateway::diagnostics_commands::diagnostics_events_list,
            gateway::diagnostics_commands::diagnostics_terminal_consistency_run,
            gateway::diagnostics_commands::diagnostics_chat_consistency_run,
            gateway::diagnostics_commands::diagnostics_overview_get,
            gateway::diagnostics_commands::diagnostics_export_generate,
            gateway::member_commands::members_list,
            gateway::member_commands::member_invite,
            gateway::member_commands::member_remove,
            gateway::member_commands::member_profile_update,
            gateway::member_commands::member_status_update,
            gateway::orchestration_commands::orchestration_dispatch_chat_message,
            gateway::orchestration_commands::orchestration_resume_member_dispatch_queue,
            gateway::notification_commands::notification_preferences_get,
            gateway::notification_commands::notification_preferences_update,
            gateway::notification_commands::notification_unread_summary_get,
            gateway::notification_commands::notification_unread_summary_update,
            gateway::notification_commands::notification_navigation_pending_get,
            gateway::notification_commands::notification_navigation_dispatch,
            gateway::notification_commands::notification_ignore_all_unread,
            gateway::notification_commands::notification_preview_hover,
            gateway::notification_commands::notification_preview_hide,
            gateway::skills_commands::skills_library_list,
            gateway::skills_commands::skills_import_folder,
            gateway::skills_commands::skills_open_folder,
            gateway::skills_commands::skills_delete,
            gateway::skills_commands::workspace_skill_links_list,
            gateway::skills_commands::workspace_skill_link,
            gateway::skills_commands::workspace_skill_unlink,
            gateway::roadmap_commands::roadmap_tasks_list,
            gateway::roadmap_commands::roadmap_task_create,
            gateway::roadmap_commands::roadmap_task_update,
            gateway::roadmap_commands::roadmap_task_delete,
            gateway::roadmap_commands::roadmap_goals_list,
            gateway::roadmap_commands::roadmap_goal_create,
            gateway::roadmap_commands::roadmap_goal_update,
            gateway::roadmap_commands::roadmap_goal_delete,
            gateway::settings_commands::profile_settings_get,
            gateway::settings_commands::profile_settings_update,
            gateway::settings_commands::profile_avatar_upload,
            gateway::settings_commands::profile_avatar_preset_select,
            gateway::settings_commands::profile_avatar_reset,
            gateway::settings_commands::profile_avatar_delete_uploaded,
            gateway::settings_commands::shortcut_preferences_get,
            gateway::settings_commands::shortcut_preferences_update,
            gateway::settings_commands::shortcut_preferences_reset,
            gateway::settings_commands::chat_terminal_output_preferences_get,
            gateway::settings_commands::chat_terminal_output_preferences_update,
            gateway::settings_commands::chat_terminal_output_preferences_reset,
            gateway::settings_commands::terminal_configuration_get,
            gateway::settings_commands::terminal_configuration_update,
            gateway::settings_commands::terminal_configuration_reset,
            gateway::terminal_commands::terminal_open,
            gateway::terminal_commands::terminal_attach,
            gateway::terminal_commands::terminal_input,
            gateway::terminal_commands::terminal_resize,
            gateway::terminal_commands::terminal_close,
            gateway::terminal_commands::terminal_tabs_list,
            gateway::terminal_commands::terminal_environments_list,
            gateway::terminal_commands::terminal_tab_create,
            gateway::terminal_commands::terminal_tab_close,
            gateway::terminal_commands::terminal_tab_restore,
            gateway::terminal_commands::terminal_tab_update,
            gateway::contact_commands::contacts_list,
            gateway::contact_commands::contact_create,
            gateway::contact_commands::contact_update,
            gateway::contact_commands::contact_delete,
            gateway::chat_commands::chat_conversations_list,
            gateway::chat_commands::chat_group_conversation_create,
            gateway::chat_commands::chat_message_send,
            gateway::chat_commands::chat_conversation_settings_update,
            gateway::chat_commands::chat_conversation_clear,
            gateway::chat_commands::chat_data_repair,
            gateway::chat_commands::chat_data_clear,
            gateway::chat_commands::chat_conversation_delete,
            gateway::chat_commands::chat_messages_page,
            gateway::chat_commands::chat_read_position_update,
            gateway::chat_commands::chat_group_conversation_members_update,
            gateway::chat_commands::chat_private_conversation_start
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
